SSD support
dividiti/ck-caffe pull request #95
Opened 2017-04-14 04:55 UTC by Rhymmor

#85  
In this PR:
- Two packages with Caffe SSD libraries (CPU and GPU with CUDA
- Corresponding programs for SSD detection (only with default mode)
- COCO-2014, VOC-2007, VOC-2012 datasets
- Pretrained SSD 300 and 512 models (trained on COCO and VOC)

2017-04-14 05:27 UTC, DVEfremov requested changes
please tack a look and le'ts discus verbally

2017-04-14 05:27 UTC, DVEfremov commented on package/lib-caffe-ssd-cpu/.cm/meta.json
> +        "PACKAGE_CONFIGURE_FLAGS_ANDROID": "-DBUILD_python=OFF -DBUILD_docs=OFF -DUSE_HDF5=OFF",
some package unified some are not

2017-04-14 05:27 UTC, DVEfremov commented on package/caffemodel-ssd-voc-300/.cm/meta.json
> +    "windows",
can't see bat file (only install.sh)
have you  tried it run on windows ?

2017-04-14 05:38 UTC, Rhymmor commented on package/caffemodel-ssd-voc-300/.cm/meta.json
> +    "windows",
No, only for linux right now

2017-04-17 06:06 UTC, dsavenko commented on package/caffemodel-ssd-voc-300/.cm/meta.json
> +    "windows",
In this case it shouldn't mention 'windows' in the meta.

2017-05-18 09:48 UTC, dsavenko commented
Will provide an updated PR soon.

2017-05-18 09:48 UTC, closed without merging